// Preload: safe IPC bridge exposed to the sheet renderer as window.api.
import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("api", {
  loadCharacter: (id: string) => ipcRenderer.invoke("load-character", id),
  listCharacters: () => ipcRenderer.invoke("list-characters"),
  listToggles: (request: unknown) => ipcRenderer.invoke("list-toggles", request),
  roll: (request: unknown, enabledToggleIds: string[]) =>
    ipcRenderer.invoke("roll", request, enabledToggleIds),
  // D&D Beyond pane + slot sync (drives the real sheet)
  setRightPane: (mode: "roll20" | "ddb") => ipcRenderer.invoke("set-right-pane", mode),
  ddbStatus: () => ipcRenderer.invoke("ddb-status"),
  ddbAuth: () => ipcRenderer.invoke("ddb-auth"),
  ddbSync: () => ipcRenderer.invoke("ddb-sync"),
  ddbPeek: () => ipcRenderer.invoke("ddb-peek"),
  ddbSpend: (level: number) => ipcRenderer.invoke("ddb-spend", level),
  ddbRestore: (level: number) => ipcRenderer.invoke("ddb-restore", level),
  ddbRestoreAll: () => ipcRenderer.invoke("ddb-restore-all"),
  ddbHitDiceRead: () => ipcRenderer.invoke("ddb-hd-read"),
  ddbHitDiceStage: (count: number, die?: number) => ipcRenderer.invoke("ddb-hd-stage", count, die),
  ddbHitDiceReset: () => ipcRenderer.invoke("ddb-hd-reset"),
  ddbShortRest: (count: number, die?: number) => ipcRenderer.invoke("ddb-short-rest", count, die),
  ddbItemSetQty: (id: number, quantity: number) => ipcRenderer.invoke("ddb-item-set-qty", id, quantity),
  inventoryRefresh: () => ipcRenderer.invoke("inventory-refresh"),
  ddbOpenInventory: () => ipcRenderer.invoke("ddb-open-inventory"),
  ddbSetHp: (removed: number, temp: number) => ipcRenderer.invoke("ddb-set-hp", removed, temp),
  ddbSetCondition: (id: number, active: boolean, level: number | null) => ipcRenderer.invoke("ddb-set-condition", id, active, level),
  r20SetTokenHp: (name: string, current: number, max: number, temp?: number) => ipcRenderer.invoke("r20-token-hp", name, current, max, temp),
  r20SelectedToken: () => ipcRenderer.invoke("r20-selected-token"),
  r20ListTokens: () => ipcRenderer.invoke("r20-list-tokens"),
  r20SetTokenHpById: (id: string, current: number, max: number, temp?: number) => ipcRenderer.invoke("r20-token-hp-by-id", id, current, max, temp),
  r20FindToken: (name: string, max: number) => ipcRenderer.invoke("r20-token-find", name, max),
  ddbReadAc: () => ipcRenderer.invoke("ddb-read-ac"),
  roll20Scrape: () => ipcRenderer.invoke("roll20-scrape"),
  roll20Say: (message: string, speakingAs?: string) => ipcRenderer.invoke("roll20-say", message, speakingAs),
  roll20SheetStyle: () => ipcRenderer.invoke("roll20-sheet-style"),
  r20TurnTop: () => ipcRenderer.invoke("r20-turn-top"),
  notify: (title: string, body: string) => ipcRenderer.invoke("notify", title, body),
  // Session log & statistics
  sessionSync: () => ipcRenderer.invoke("session-sync"),
  sessionDeepSync: () => ipcRenderer.invoke("session-deep-sync"),
  sessionClear: () => ipcRenderer.invoke("session-clear"),
  sessionExport: (kind: "json" | "csv-log" | "csv-stats") => ipcRenderer.invoke("session-export", kind),
  copyText: (text: string) => ipcRenderer.invoke("copy-text", text),
  logout: () => ipcRenderer.invoke("logout"),
  launchApp: (config: { source: string; vtt: string }) => ipcRenderer.invoke("launch-app", config),
  getConfig: () => ipcRenderer.invoke("get-config"),
  showSplash: () => ipcRenderer.invoke("show-splash"),
  loadPoke5e: (input: string) => ipcRenderer.invoke("load-poke5e", input),
  listPoke5eTrainers: (extraKeys: string[]) => ipcRenderer.invoke("list-poke5e-trainers", extraKeys),
  poke5eGmRoster: (extraKeys: string[]) => ipcRenderer.invoke("poke5e-gm-roster", extraKeys),
  loadPoke5ePokemon: (pokemonId: number) => ipcRenderer.invoke("load-poke5e-pokemon", pokemonId),
  poke5eSetHp: (curHp: number, maxHp: number) => ipcRenderer.invoke("poke5e-set-hp", curHp, maxHp),
  poke5eSetPp: (learnedId: number, moveId: string, ppCur: number, ppMax: number, notes?: string) => ipcRenderer.invoke("poke5e-set-pp", learnedId, moveId, ppCur, ppMax, notes),
  poke5eKeys: () => ipcRenderer.invoke("poke5e-keys"),
  searchMonsters: (query: string) => ipcRenderer.invoke("search-monsters", query),
  loadMonster: (slug: string) => ipcRenderer.invoke("load-monster", slug),
  searchDdbMonsters: (query: string) => ipcRenderer.invoke("search-ddb-monsters", query),
  loadDdbMonster: (id: string) => ipcRenderer.invoke("load-ddb-monster", id),
});
